import React from 'react';
import ReactDOM from 'react-dom';

import { RangeControl, TextControl, PanelBody, ToggleControl, Button } from '@wordpress/components';
import { InspectorControls, RichText, MediaUpload, PlainText } from '@wordpress/block-editor'
import { plugins as icon } from '@wordpress/icons';

const name = 'be/partial';

export { name };

export const settings = {
	title: 'Snippet',
	description:  'Add content generated by the server.',
  icon,
  category: 'widgets',
  keywords: [ 'server', 'partial' ],
  attributes: {
    name: {
      type: 'string'
    }
  },
  edit({attributes, className, setAttributes, isSelected}) {
    return ([
      <InspectorControls>
				<PanelBody title='Snippet settings'>
          <TextControl
              label="Name"
              value={ className }
                    value={ attributes.name }
                    onChange={ ( content ) => setAttributes( { name: content } ) }
          />
				</PanelBody>
      </InspectorControls>,
      <div className={ className }>
        <p>Snippet Content</p>
        <div className='be-partial-outline'>
        </div>
      </div>
    ]);
  }
};
